{% set name = "climb-onyx-client" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e936329131d113bfb2c16fa6458c42c7de94a40e7673a8916c82165375ca18f2

build:
  entry_points:
    - onyx = onyx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - requests ~=2.32
    - click ~=8.1.7
    - typer ~=0.12.3
    - rich ~=13.9.4

test:
  imports:
    - onyx
  commands:
    - pip check
    - onyx --help
    - onyx
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CLIMB-TRE/onyx-client
  summary: Client program for interacting with Onyx.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aresti
    - tombch
