{% set name = "climb-onyx-client" %}
{% set version = "4.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b4ada6e3c6693721fd9a22d929f904019582b0ef053b417b97335ff7b8faeee6

build:
  entry_points:
    - onyx = onyx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - typer >=0.6.0
    - rich

test:
  imports:
    - onyx
  commands:
    - pip check
    - onyx --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CLIMB-TRE/onyx-client
  summary: Client program for interacting with Onyx.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tombch
