{% set name = "climb-onyx-client" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climb-onyx-client-{{ version }}.tar.gz
  sha256: adaeef5782f2aea0008378e09e27e7bcff8d718ac091076d40f6be33e50333f8

build:
  entry_points:
    - onyx = onyx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - typer >=0.6.0
    - rich

test:
  imports:
    - onyx
  commands:
    - pip check
    - onyx --help
  requires:
    - pip

about:
  home: https://github.com/CLIMB-TRE/onyx-client
  summary: Client program for interacting with Onyx.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tombch
