{% set name = "climb-onyx-client" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 90c2c33bd8106d1fe80a6c2060308c089a57e0a2e0fa5839a7215a47e9ea18fd

build:
  entry_points:
    - onyx = onyx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python =3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - requests
    - typer >=0.6.0
    - rich

test:
  imports:
    - onyx
  commands:
    - pip check
    - onyx --help
  requires:
    - python =3.7
    - pip

about:
  home: https://github.com/CLIMB-TRE/onyx-client
  summary: Client program for interacting with Onyx.
  license: GPL-2.0-or-later
  license_file: LICENSE
  license_family: GPL

extra:
  recipe-maintainers:
    - tombch
