{% set name = "climb-onyx-client" %}
{% set version = "4.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0203fdf60add0c8c833e256bdbe083fa9a9c3b19d4898f6207e520822fa1f66c

build:
  entry_points:
    - onyx = onyx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - requests ~=2.32
    - click ~=8.1.7
    - typer ~=0.12.3
    - rich ~=13.9.4

test:
  imports:
    - onyx
  commands:
    - pip check
    - onyx --help
    - onyx
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CLIMB-TRE/onyx-client
  summary: Client program for interacting with Onyx.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tombch
