{% set name = "climb-onyx-client" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climb-onyx-client-{{ version }}.tar.gz
  sha256: 5a12868a8c0f52795c6f3728de194328b44d61cc48e87d896f61e4d3a4f1f9f4

build:
  entry_points:
    - onyx = onyx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - typer >=0.6.0
    - rich

test:
  imports:
    - onyx
  commands:
    - pip check
    - onyx --help
  requires:
    - pip

about:
  home: https://github.com/CLIMB-TRE/onyx-client
  summary: Client program for interacting with Onyx.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tombch
